//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionnaire_de_depenses
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestion_depensesEntities : DbContext
    {
        public gestion_depensesEntities()
            : base("name=gestion_depensesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Budget> Budget { get; set; }
        public virtual DbSet<tirelire> tirelire { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
        public virtual DbSet<Utilisateurs> Utilisateurs { get; set; }
    }
}
