//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionnaire_de_depenses
{
    using System;
    using System.Collections.Generic;
    
    public partial class tirelire
    {
        public int ID_Tirelire { get; set; }
        public string Nom_Tirelire { get; set; }
        public Nullable<double> Montant { get; set; }
        public string Description { get; set; }
        public string Utilisateur_Username { get; set; }
    
        public virtual Utilisateurs Utilisateurs { get; set; }
    }
}
