//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionnaire_de_depenses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int ID_Transactions { get; set; }
        public string Nom_Transactions { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Categorie { get; set; }
        public string Utilisateur_Username { get; set; }
        public int Budget_IDB { get; set; }
    
        public virtual Budget Budget { get; set; }
        public virtual Utilisateurs Utilisateurs { get; set; }
    }
}
